[package]
name = "ssj_june2023"
version = "0.1.0"
edition = "2021"
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.10", default-features = false }

[features]
default = ["client"]
client = ["bevy/default"]
server = []
